# Site setings
name: 'The Boy Wonders'
description: 'A Blog by Robin Howlett'
meta_description: 'Code, management, and horse racing by Robin Howlett'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage_robin-gravatar.png'
  greetings: "I'm Robin Howlett, Director of Engineering at <a href=\"https://www.snaplogic.com/\">SnapLogic</a>, the Intelligent 
      Integration Platform. Married to <a href=\"http://sarahhowlett.com/\">Sarah Howlett</a>. Father of twins. Boulder, 
      Colorado-based. Made in Ireland."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: http://www.robinhowlett.com/
disqus: 'robinhowlett'
#mailchimp_url: '//mailchi.mp/aba2a859dd29/subscribe-for-updates'
# Add your GA Tracking Id
ga_analytics: UA-35552317-2

# Contact form setings
email: robin.howlett@gmail.com
contact_page_description: "Ask me a question."
thankyou_page_description: "Your message has been successfully sent."

# Social links
twitter: 'robinhowlett'
github: 'robinhowlett'
linkedin: 'robinhowlett'

# Navigation
navigation:
 - text: Home
   url: /
 - text: Code
   url: /tag/code/
 - text: Horse Racing
   url: /tag/horseracing/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist

# Pagination
paginate: 5
paginate_path: /page:num/

excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!-- more -->"

# Permalinks
permalink: "/blog/:year/:month/:day/:title/"

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
